services:
  soil:
    build: .
    ports:
      # Change 80 to the port you want to run Soil on
      - "80:3000"
    volumes:
      # Edit this path if you have soil.config.yaml stashed elsewhere
      - ./soil.config.yaml:/home/node/app/soil.config.yaml
      - ./staticData.json:/home/node/app/staticData.json