content:
  - block: |
      ### **_{{ sys.hostname }}_ @ {{ pre.sysName }}**

      Hello and welcome to _Soil_.

      If you know your party's extension, you may dial it at any time.

  - row:
    - text: "{{ pre.osName }}"
    - text: "{{ pre.localeTime }}"
  - row:
    - text: ""
    - text: "Uptime: {{ pre.uptimeClock }}"

  - row:
    - text: "{{ pre.cpuName }}"
      size: 3
    - text: "{{ fix(100*cpu.load, 2) }}%"
      bars:
        - fracx: cpu.load
          color: '#ccc'
        - color: '#eee'
  - row:
    - size: 3
    - text: "{{ cpu.temp.main }}°C"
      bars:
        - fracx: clamp(cpu.temp.main - 35, 0, 40)/40
          color: '#ccc'
        - color: '#eee'
  - row:
    - text: "{{ fix(pre.memTotalGiB, 2) }}GiB RAM"
      size: 3
    - text: "{{ fix(100 * pre.memUsedFrac, 2) }}%"
      bars:
        - fracx: pre.memUsedFrac
          color: '#ccc'
        - color: '#eee'