content:
  main:
    - block: |
        # Hello Soil!

        Welcome to your Soil Startpage! Here you can host:
        - Dynamic system stats
        - Bookmarks and links
        - Any other Markdown content you want

        Check out your **soil.config.yaml** to start customizing.

        ---

    - row:
      - text: "**System**"
      - text: "{{ sys.hostname }} @ {{ pre.sysName }}"
        size: 7
    - row:
      - text: "**OS**"
      - text: "{{ pre.osName }}"
        size: 7
    - row:
      - text: "**CPU**"
      - text: "{{ pre.cpuName }}"
        size: 7
    - row:
      - text: "**Uptime**"
      - text: "{{ pre.uptimeClock }}"
        size: 7
    - row:
      - text: CPU ({{ fix(100 * cpu.load, 2) }}%)
        bars:
        - fracx: cpu.load
          color: bar
        - color: bar-bg
      - text: Memory ({{ fix(100 * pre.memUsedFrac, 2) }}%)
        bars:
        - fracx: pre.memUsedFrac
          color: bar
        - color: bar-bg
  
    - block: ---

    - row:
      - text: "[Soil](https://github.com/NeillJohnston/soil)"
      - text: "[Link](http://example.com/)"
      - text: "[Link](http://example.com/)"
    - row:
      - text: "[Link](http://example.com/)"
      - text: "[Link](http://example.com/)"
      - text: "[Link](http://example.com/)"
    - row:
      - text: "[Link](http://example.com/)"
      - text: "[Link](http://example.com/)"
      - text: "[Link](http://example.com/)"

  footer:
    - widget: theme-switcher

theme:
  light:
    bg: "#fff"
    text: "#000"
    bar: "#ccc"
    bar-bg: "#eee"
    
  dark:
    bg: "#000"
    text: "#fff"
    bar: "#444"
    bar-bg: "#222"